export const ACCOUNT_ACTIVATION_REQUEST_SENDING = 'ACCOUNT_ACTIVATION_REQUEST_SENDING';
export type T_ACCOUNT_ACTIVATION_REQUEST_SENDING = typeof ACCOUNT_ACTIVATION_REQUEST_SENDING;

export const ACCOUNT_ACTIVATION_REQUEST_FAILED = 'ACCOUNT_ACTIVATION_REQUEST_FAILED';
export type T_ACCOUNT_ACTIVATION_REQUEST_FAILED = typeof ACCOUNT_ACTIVATION_REQUEST_FAILED;

export const ACCOUNT_ACTIVATION_REQUEST_SUCCESS = 'ACCOUNT_ACTIVATION_REQUEST_SUCCESS';
export type T_ACCOUNT_ACTIVATION_REQUEST_SUCCESS = typeof ACCOUNT_ACTIVATION_REQUEST_SUCCESS;

export const NEW_ACTIVATOR_REQUEST_SENDING = 'NEW_ACTIVATOR_REQUEST_SENDING';
export type T_NEW_ACTIVATOR_REQUEST_SENDING = typeof NEW_ACTIVATOR_REQUEST_SENDING;

export const NEW_ACTIVATOR_REQUEST_FAILED = 'NEW_ACTIVATOR_REQUEST_FAILED';
export type T_NEW_ACTIVATOR_REQUEST_FAILED = typeof NEW_ACTIVATOR_REQUEST_FAILED;

export const NEW_ACTIVATOR_REQUEST_SUCCESS = 'NEW_ACTIVATOR_REQUEST_SUCCESS';
export type T_NEW_ACTIVATOR_REQUEST_SUCCESS = typeof NEW_ACTIVATOR_REQUEST_SUCCESS;