export const REGISTRATION_REQUEST_SENDING = 'REGISTRATION_REQUEST_SENDING';
export type T_REGISTRATION_REQUEST_SENDING = typeof REGISTRATION_REQUEST_SENDING;

export const REGISTRATION_REQUEST_SUCCESS = 'REGISTRATION_REQUEST_SUCCESS';
export type T_REGISTRATION_REQUEST_SUCCESS = typeof REGISTRATION_REQUEST_SUCCESS;

export const REGISTRATION_REQUEST_FAILED = 'REGISTRATION_REQUEST_FAILED';
export type T_REGISTRATION_REQUEST_FAILED = typeof REGISTRATION_REQUEST_FAILED;