export const UPLOAD_AVATAR_TO_IMAGEBB_BEGIN = 'UPLOAD_AVATAR_TO_IMAGEBB_BEGIN';
export type T_UPLOAD_AVATAR_TO_IMAGEBB_BEGIN = typeof UPLOAD_AVATAR_TO_IMAGEBB_BEGIN;

export const UPLOAD_AVATAR_TO_IMAGEBB_FAILED  = 'UPLOAD_AVATAR_TO_IMAGEBB_FAILED';
export type T_UPLOAD_AVATAR_TO_IMAGEBB_FAILED = typeof UPLOAD_AVATAR_TO_IMAGEBB_FAILED;

export const UPLOAD_AVATAR_TO_IMAGEBB_SUCCESS = 'UPLOAD_AVATAR_TO_IMAGEBB_SUCCESS';
export type T_UPLOAD_AVATAR_TO_IMAGEBB_SUCCESS = typeof UPLOAD_AVATAR_TO_IMAGEBB_SUCCESS;

export const UPDATE_AVATAR_REQUEST_SENDING = 'UPDATE_AVATAR_REQUEST_SENDING';
export type T_UPDATE_AVATAR_REQUEST_SENDING = typeof UPDATE_AVATAR_REQUEST_SENDING;

export const UPDATE_AVATAR_REQUEST_FAILED = 'UPDATE_AVATAR_REQUEST_FAILED';
export type T_UPDATE_AVATAR_REQUEST_FAILED = typeof UPDATE_AVATAR_REQUEST_FAILED;

export const UPDATE_AVATAR_REQUEST_SUCCESS = 'UPDATE_AVATAR_REQUEST_SUCCESS';
export const T_UPDATE_AVATAR_REQUEST_SUCCESS = typeof UPDATE_AVATAR_REQUEST_SUCCESS;