CREATE TABLE [dbo].[ChatGroup] (
	Id INT IDENTITY(1,1) NOT NULL,
	ThingId INT DEFAULT NULL,
	GroupType TINYINT NOT NULL DEFAULT 0,
	GroupTitle NVARCHAR(50) DEFAULT NULL,
	GroupAvatar NVARCHAR(150) DEFAULT NULL,
	CreatedOn DATETIME2(7) DEFAULT (GETDATE()),
	CONSTRAINT [PK_ChatGroup_Id] PRIMARY KEY ([Id] ASC)
)
