export const AUTHENTICATED = 'AUTHENTICATED';
export type TAUTHENTICATED = typeof AUTHENTICATED;

export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export type TUNAUTHENTICATED = typeof UNAUTHENTICATED;