CREATE TABLE [dbo].[HidroStore] (
	Id INT IDENTITY(1,1) NOT NULL,
	StoreName NVARCHAR(70) DEFAULT NULL,
	StoreLogo NVARCHAR(150) DEFAULT NULL,
	Introduction NVARCHAR(4000) DEFAULT NULL,
	CustomTheme NVARCHAR(MAX) DEFAULT NULL,
	OpenedOn DATETIME2(7) DEFAULT (GETDATE()), 
	CONSTRAINT [PK_HidroStore_Id] PRIMARY KEY ([Id] ASC)
)