CREATE TABLE [dbo].[StoreRole] (
	Id INT IDENTITY(1,1) NOT NULL,
	RoleName NVARCHAR(30) DEFAULT NULL,
	[Description] NVARCHAR(300) DEFAULT NULL,
	CONSTRAINT [PK_StoreRole_Id] PRIMARY KEY ([Id] ASC)
)
