export const AUTHENTICATION_SENDING = 'AUTHENTICATION_SENDING';
export type T_AUTHENTICATION_SENDING = typeof AUTHENTICATION_SENDING;

export const AUTHENTICATED = 'AUTHENTICATED';
export type T_AUTHENTICATED = typeof AUTHENTICATED;

export const SIGN_OUT_SENDING = 'SIGN_OUT_SENDING';
export type T_SIGN_OUT_SENDING = typeof SIGN_OUT_SENDING;

export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
export type T_SIGN_OUT_FAILED = typeof SIGN_OUT_FAILED;

// When sign-in failed
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export type T_UNAUTHENTICATED = typeof UNAUTHENTICATED;

//When sign-out success
export const NO_AUTHENTICATION = 'NO_AUTHENTICATION';
export type T_NO_AUTHENTICATION = typeof NO_AUTHENTICATION;

export const LOAD_AUTH_USER = 'LOAD_AUTH_USER';
export type T_LOAD_AUTH_USER = typeof LOAD_AUTH_USER;

export const LOAD_AUTH_USER_FAILED = 'LOAD_AUTH_USER_FAILED';
export type T_LOAD_AUTH_USER_FAILED = typeof LOAD_AUTH_USER_FAILED;