CREATE TABLE [dbo].[Country] (
	Id INT IDENTITY(1,1) NOT NULL,
	CountryName NVARCHAR(50) DEFAULT NULL,
	CountryCode NVARCHAR(5) DEFAULT NULL,
	Continent NVARCHAR(30) DEFAULT NULL,
	CurrencyCode NVARCHAR(5) DEFAULT NULL,
	CurrencyName NVARCHAR(30) DEFAULT NULL,
	CONSTRAINT [PK_Country_Id] PRIMARY KEY ([Id] ASC)
)
