CREATE TABLE [dbo].[FineLocation] (

	Id INT IDENTITY(1, 1) NOT NULL,
	BuildingName NVARCHAR(50) DEFAULT NULL,
	StreetAddress NVARCHAR(50) DEFAULT NULL,
	AlternateAddress NVARCHAR(50) DEFAULT NULL,
	[Group] NVARCHAR(3) DEFAULT NULL, --To
	Lane NVARCHAR(10) DEFAULT NULL, --Ngo, ngach
	[Quarter] NVARCHAR(40) DEFAULT NULL, --Khu pho
	Hamlet NVARCHAR(40) DEFAULT NULL, --Ap
	Commute NVARCHAR(40) DEFAULT NULL, --Xa
	Ward NVARCHAR(40) DEFAULT NULL, --Phuong
	District NVARCHAR(40) DEFAULT NULL, --Quan
	Town NVARCHAR(40) DEFAULT NULL, --Thi xa
	Suburb NVARCHAR(50) DEFAULT NULL,
	Postcode NVARCHAR(10) DEFAULT NULL,
	Province NVARCHAR(40) DEFAULT NULL, --Tinh
	City NVARCHAR(40) DEFAULT NULL,
	[State] NVARCHAR(40) DEFAULT NULL,
	Country NVARCHAR(40) DEFAULT NULL,
	IsStandard BIT NOT NULL DEFAULT 0,
	Note NVARCHAR(255) DEFAULT NULL,
	CONSTRAINT [PK_FineLocation_Id] PRIMARY KEY ([Id] ASC)
);