CREATE TABLE [dbo].[HidroProfile] (

	Id INT IDENTITY(1,1) NOT NULL,
	HidrogenianId INT NOT NULL,
	CitizenCardPhoto NVARCHAR(70) DEFAULT NULL,
	CitizenCardNumber NVARCHAR(15) DEFAULT NULL,
	CitizenCardIssuedDate DATETIME2(7) DEFAULT NULL,
	AvatarInformation NVARCHAR(1000) DEFAULT NULL,
	DateOfBith DATETIME2(7) DEFAULT NULL,
	Gender BIT DEFAULT NULL,
	Ethnicity NVARCHAR(30) DEFAULT NULL,
	FamilyName NVARCHAR(30) DEFAULT NULL,
	GivenName NVARCHAR(50) DEFAULT NULL,
	Company NVARCHAR(30) DEFAULT NULL,
	JobTitle NVARCHAR(30) DEFAULT NULL,
	SelfIntroduction NVARCHAR(500) DEFAULT NULL,
	PersonalWebsite NVARCHAR(100) DEFAULT NULL
	CONSTRAINT [PK_HidroProfile_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_HidroProfile_Hidrogenian] FOREIGN KEY ([HidrogenianId]) REFERENCES [dbo].[Hidrogenian] ([Id]) ON DELETE CASCADE
)
