CREATE TABLE [dbo].[Location] (

	Id INT IDENTITY(1, 1) NOT NULL,
	BuildingName NVARCHAR(50) DEFAULT NULL,
	StreetAddress NVARCHAR(50) DEFAULT NULL,
	AlternateAddress NVARCHAR(50) DEFAULT NULL,
	Lane NVARCHAR(10) DEFAULT NULL,
	[Quarter] NVARCHAR(30) DEFAULT NULL,
	Hamlet NVARCHAR(30) DEFAULT NULL,
	Commute NVARCHAR(30) DEFAULT NULL,
	Ward NVARCHAR(30) DEFAULT NULL,
	District NVARCHAR(30) DEFAULT NULL,
	Suburb NVARCHAR(50) DEFAULT NULL,
	Postcode NVARCHAR(10) DEFAULT NULL,
	Province NVARCHAR(30) DEFAULT NULL,
	City NVARCHAR(30) DEFAULT NULL,
	Country NVARCHAR(30) DEFAULT NULL,
	Note NVARCHAR(255) DEFAULT NULL,
	CONSTRAINT [PK_Location_Id] PRIMARY KEY ([Id] ASC)
);