export const GET_WATER_API_KEY = 'GET_WATER_API_KEY';
export type T_GET_WATER_API_KEY = typeof GET_WATER_API_KEY;

export const GET_WATER_API_KEY_FAILED = 'GET_WATER_API_KEY_FAILED';
export type T_GET_WATER_API_KEY_FAILED = typeof GET_WATER_API_KEY_FAILED;

export const UPLOAD_AVATAR_TO_WATER_BEGIN = 'UPLOAD_AVATAR_TO_WATER_BEGIN';
export type T_UPLOAD_AVATAR_TO_WATER_BEGIN = typeof UPLOAD_AVATAR_TO_WATER_BEGIN;

export const UPLOAD_AVATAR_TO_WATER_FAILED  = 'UPLOAD_AVATAR_TO_WATER_FAILED';
export type T_UPLOAD_AVATAR_TO_WATER_FAILED = typeof UPLOAD_AVATAR_TO_WATER_FAILED;

export const UPLOAD_AVATAR_TO_WATER_SUCCESS = 'UPLOAD_AVATAR_TO_WATER_SUCCESS';
export type T_UPLOAD_AVATAR_TO_WATER_SUCCESS = typeof UPLOAD_AVATAR_TO_WATER_SUCCESS;

export const UPDATE_AVATAR_REQUEST_SENDING = 'UPDATE_AVATAR_REQUEST_SENDING';
export type T_UPDATE_AVATAR_REQUEST_SENDING = typeof UPDATE_AVATAR_REQUEST_SENDING;

export const UPDATE_AVATAR_REQUEST_FAILED = 'UPDATE_AVATAR_REQUEST_FAILED';
export type T_UPDATE_AVATAR_REQUEST_FAILED = typeof UPDATE_AVATAR_REQUEST_FAILED;

export const UPDATE_AVATAR_REQUEST_SUCCESS = 'UPDATE_AVATAR_REQUEST_SUCCESS';
export type T_UPDATE_AVATAR_REQUEST_SUCCESS = typeof UPDATE_AVATAR_REQUEST_SUCCESS;

export const REMOVE_AVATAR_REQUEST_SENDING = 'REMOVE_AVATAR_REQUEST_SENDING';
export type T_REMOVE_AVATAR_REQUEST_SENDING = typeof REMOVE_AVATAR_REQUEST_SENDING;

export const REMOVE_AVATAR_REQUEST_SUCCESS = 'REMOVE_AVATAR_REQUEST_SUCCESS';
export type T_REMOVE_AVATAR_REQUEST_SUCCESS = typeof REMOVE_AVATAR_REQUEST_SUCCESS;

export const REMOVE_AVATAR_REQUEST_FAILED = 'REMOVE_AVATAR_REQUEST_FAILED';
export type T_REMOVE_AVATAR_REQUEST_FAILED = typeof REMOVE_AVATAR_REQUEST_FAILED;