CREATE TABLE [dbo].[ItemBundle] (
	Id INT IDENTITY(1, 1) NOT NULL,
	ItemId INT NOT NULL,
	BundleName NVARCHAR(30) DEFAULT NULL,
	AvatarData NVARCHAR(100) DEFAULT NULL,
	BundlePrice DECIMAL NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ItemBundle_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_ItemBundle_Item] FOREIGN KEY ([ItemId]) REFERENCES Item ([Id])
)
