CREATE TABLE [dbo].[ItemAsset] (
	Id INT IDENTITY(1,1) NOT NULL,
	ItemId INT NOT NULL,
	AssetName NVARCHAR(250) DEFAULT NULL,
	AssetLocation NVARCHAR(150) DEFAULT NULL,
	IsPhoto BIT NOT NULL DEFAULT 0,
	IncludeInBody BIT NOT NULL DEFAULT 0,
	IncludeInCover BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ItemAsset_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_ItemAsset_Item] FOREIGN KEY ([ItemId]) REFERENCES Item ([Id])
)