CREATE TABLE [dbo].[Item] (
	Id INT IDENTITY(1,1) NOT NULL,
	ListingId INT NOT NULL,
	ItemPrice DECIMAL NOT NULL DEFAULT 0,
	ItemName NVARCHAR(30) DEFAULT NULL,
	CONSTRAINT [PK_Item_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_Item_Listing] FOREIGN KEY ([ListingId]) REFERENCES Listing ([Id])
)
