CREATE TABLE [dbo].[Order] (
	Id INT IDENTITY(1, 1) NOT NULL,
	CartId INT NOT NULL,
	OrderTotal DECIMAL NOT NULL DEFAULT 0,
	IsFullyPaid BIT DEFAULT NULL,
	MadeOn DATETIME2(7) NOT NULL DEFAULT (GETDATE()),
	CONSTRAINT [PK_Order_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_Order_ShoppingCart] FOREIGN KEY ([CartId]) REFERENCES ShoppingCart ([Id])
)
