export const PASSWORD_RECOVERY_REQUEST_SENDING = 'PASSWORD_RECOVERY_REQUEST_SENDING';
export type T_PASSWORD_RECOVERY_REQUEST_SENDING = typeof PASSWORD_RECOVERY_REQUEST_SENDING;

export const PASSWORD_RECOVERY_REQUEST_SUCCESS = 'PASSWORD_RECOVERY_REQUEST_SUCCESS';
export type T_PASSWORD_RECOVERY_REQUEST_SUCCESS = typeof PASSWORD_RECOVERY_REQUEST_SUCCESS;

export const PASSWORD_RECOVERY_REQUEST_FAILED = 'PASSWORD_RECOVERY_REQUEST_FAILED';
export type T_PASSWORD_RECOVERY_REQUEST_FAILED = typeof PASSWORD_RECOVERY_REQUEST_FAILED;

export const FORGOT_PASSWORD_REQUEST_SENDING = 'FORGOT_PASSWORD_REQUEST_SENDING';
export type T_FORGOT_PASSWORD_REQUEST_SENDING = typeof FORGOT_PASSWORD_REQUEST_SENDING;

export const FORGOT_PASSWORD_REQUEST_SUCCESS = 'FORGOT_PASSWORD_REQUEST_SUCCESS';
export type T_FORGOT_PASSWORD_REQUEST_SUCCESS = typeof FORGOT_PASSWORD_REQUEST_SUCCESS;

export const FORGOT_PASSWORD_REQUEST_FAILED = 'FORGOT_PASSWORD_REQUEST_FAILED';
export type T_FORGOT_PASSWORD_REQUEST_FAILED = typeof FORGOT_PASSWORD_REQUEST_FAILED;